language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: dHtT70JwVRrRlNo+G5QJ40psfjLv/6yXnruLwvuX15lEFe68bVFQb5ojOQlSlcd8XFgItWjpqfSHiJPZFqyCG7pgaTNm0vr4n1mv583tvI4cJoLI3gN0WdwnanSTTV+4IEDS7s6V5eJ+/ps+PcahIofaXaB7jJgmb8EwuQGMD1E=
